CONFIGURATION=$(<./generator_config.txt)

LAST_SCRIPT_VERSION=$(echo "$CONFIGURATION" | sed -n 's/SCRIPT_VERSION=\(.*\)/\1/p')
[ "$LAST_SCRIPT_VERSION" != "$SCRIPT_VERSION" ] && echo "Script version mismatch. Please reconfigure the generator." && exit 0;

API_PROJECT_DIRECTORY=$(echo "$CONFIGURATION" | sed -n 's/API_PROJECT_DIRECTORY=\(.*\)/\1/p')
API_PROJECT_FOLDER=$(echo "$CONFIGURATION" | sed -n 's/API_PROJECT_FOLDER=\(.*\)/\1/p')
CONTROLLER_FOLDER=$(echo "$CONFIGURATION" | sed -n 's/CONTROLLER_FOLDER=\(.*\)/\1/p')
API_PROJECT_NAMESPACE=$(echo "$CONFIGURATION" | sed -n 's/API_PROJECT_NAMESPACE=\(.*\)/\1/p')
SERVICE_PROJECT_FOLDER=$(echo "$CONFIGURATION" | sed -n 's/SERVICE_PROJECT_FOLDER=\(.*\)/\1/p')
SERVICE_PROJECT_DIRECTORY=$(echo "$CONFIGURATION" | sed -n 's/SERVICE_PROJECT_DIRECTORY=\(.*\)/\1/p')
SERVICE_FOLDER=$(echo "$CONFIGURATION" | sed -n 's/SERVICE_FOLDER=\(.*\)/\1/p')
SERVICE_PROJECT_NAMESPACE=$(echo "$CONFIGURATION" | sed -n 's/SERVICE_PROJECT_NAMESPACE=\(.*\)/\1/p')

CONTROLLER_NAMESPACE=$(echo "$CONTROLLER_FOLDER" | sed -e 's/[/]/./g')
CONTROLLER_NAMESPACE=$(echo "$CONTROLLER_NAMESPACE" | sed -e 's/^[.]*//g')
CONTROLLER_NAMESPACE=$(echo "$CONTROLLER_NAMESPACE" | sed -e 's/[.]*$//g')
CONTROLLER_NAMESPACE="$API_PROJECT_NAMESPACE.$CONTROLLER_NAMESPACE"

SERVICE_NAMESPACE=$(echo "$SERVICE_FOLDER" | sed -e 's/[/]/./g')
SERVICE_NAMESPACE=$(echo "$SERVICE_NAMESPACE" | sed -e 's/^[.]*//g')
SERVICE_NAMESPACE=$(echo "$SERVICE_NAMESPACE" | sed -e 's/[.]*$//g')
SERVICE_NAMESPACE="$SERVICE_PROJECT_NAMESPACE.$SERVICE_NAMESPACE"

ROOT_FOLDER=$(readlink -m .)
SOLUTION_FOLDER=$(readlink -m $SOLUTION_FOLDER)

cd $SOLUTION_FOLDER
API_PROJECT_DIRECTORY=$(readlink -m $API_PROJECT_DIRECTORY)
API_PROJECT_FOLDER=$(readlink -m $API_PROJECT_FOLDER)
cd $API_PROJECT_FOLDER
CONTROLLER_FOLDER=$(readlink -m $CONTROLLER_FOLDER)

cd $SOLUTION_FOLDER
SERVICE_PROJECT_DIRECTORY=$(readlink -m $SERVICE_PROJECT_DIRECTORY)
SERVICE_PROJECT_FOLDER=$(readlink -m $SERVICE_PROJECT_FOLDER)
cd $SERVICE_PROJECT_FOLDER
SERVICE_FOLDER=$(readlink -m $SERVICE_FOLDER)

cd $ROOT_FOLDER
